//------------------------------------------------------------------------
// Copyright(c) 2024 Owen Stanley.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"GainEffect.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"GainEffect VST3 (64Bit)"
#else
#define stringFileDescription	"GainEffect VST3"
#endif
#define stringCompanyName		"Owen Stanley\0"
#define stringLegalCopyright	"Copyright(c) 2024 Owen Stanley."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
